App\Domain\DTO\Security\PasswordCheckDTO:
    properties:
        newpassword:
            Regex: # REGEX: at least 1 capital letter, 1 number, at least 8 characters, no space #
                pattern: '#(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])\S{8,}#'

        checknewpassword:
            Regex: # REGEX: at least 1 capital letter, 1 number, at least 8 characters, no space #
                pattern: '#(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])\S{8,}#'

